POST http://localhost:8080 /api/socks
Content-Type: application/json

{ "sock": {
  "color": "RED",
  "size": "36.0 ",
  "cottonPart": 40
 },
  "quantity": 5
}
###

PUT http://localhost:8080 /api/socks
Content-Type: application/json

{ "sock": {
  "color": "RED",
  "size": "36.0 ",
  "cottonPart": 40
},
  "quantity": 5
}
###

GET http://localhost:8080/api/socks?color=RED&size=36&cottonMin=90

###

GET http://localhost:8080/api/socks?color=RED&size=36&cottonMin=10

###

DELETE http://localhost:8080 /api/socks
Content-Type: application/json

{ "sock": {
  "color": "RED",
  "size": "36.0 ",
  "cottonPart": 40
},
  "quantity": 5
}
